package sistemaestoque;

import java.util.regex.Pattern;
import servicoBD.AlterarDAO;
import servicoBD.CadastrarDAO;
import servicoBD.Conexao;
import servicoBD.LoginDAO;

/**
 *
 * @author Igor Luciano - Igor Lacerda - Eduardo Junqueira
 */
public class Estoque extends javax.swing.JFrame {

    /**
     * Creates new form Estoque
     */
    public Estoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        Logar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        statusLogin = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TextPaneLoginLogar = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        TextAreaSenha = new javax.swing.JTextPane();
        Alterar = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextPaneUsuarioAlterar = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextPaneSenhaAlterar = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jScrollPaneNovaSenhaAlterar = new javax.swing.JScrollPane();
        jTextPaneNovaSenhaAlterar = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        statusAlterar = new javax.swing.JLabel();
        Cadastro = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextPaneEmail = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextPaneNome = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextPaneCPF = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        TextPaneSenha = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        TextPaneCSenha = new javax.swing.JTextPane();
        Cadastrar = new javax.swing.JButton();
        statusCadastro = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        TextPaneLoginCadastrar = new javax.swing.JTextPane();
        jLabel12 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Login");

        jLabel2.setText("Senha");

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        TextPaneLoginLogar.setMaximumSize(new java.awt.Dimension(3, 3));
        TextPaneLoginLogar.setMinimumSize(new java.awt.Dimension(3, 3));
        TextPaneLoginLogar.setName(""); // NOI18N
        TextPaneLoginLogar.setPreferredSize(new java.awt.Dimension(3, 3));
        jScrollPane7.setViewportView(TextPaneLoginLogar);

        jScrollPane8.setViewportView(TextAreaSenha);

        javax.swing.GroupLayout LogarLayout = new javax.swing.GroupLayout(Logar);
        Logar.setLayout(LogarLayout);
        LogarLayout.setHorizontalGroup(
            LogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogarLayout.createSequentialGroup()
                .addGroup(LogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(LogarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(statusLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LogarLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(LogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LogarLayout.createSequentialGroup()
                                .addGroup(LogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(LogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane8)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(LogarLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(btnEntrar)))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        LogarLayout.setVerticalGroup(
            LogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogarLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(LogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogarLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2))
                    .addGroup(LogarLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63)
                .addComponent(btnEntrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(statusLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jTabbedPane2.addTab("Logar", Logar);

        jScrollPane9.setViewportView(jTextPaneUsuarioAlterar);

        jLabel9.setText("Usuário");

        jScrollPane10.setViewportView(jTextPaneSenhaAlterar);

        jLabel10.setText("Nova Senha");

        jScrollPaneNovaSenhaAlterar.setViewportView(jTextPaneNovaSenhaAlterar);

        jLabel11.setText("Confirmar Senha");

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AlterarLayout = new javax.swing.GroupLayout(Alterar);
        Alterar.setLayout(AlterarLayout);
        AlterarLayout.setHorizontalGroup(
            AlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlterarLayout.createSequentialGroup()
                .addGroup(AlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AlterarLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel9))
                    .addGroup(AlterarLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(AlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(AlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAlterar)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(jScrollPane9)
                            .addComponent(jScrollPaneNovaSenhaAlterar)
                            .addComponent(statusAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        AlterarLayout.setVerticalGroup(
            AlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlterarLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(AlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AlterarLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel9))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AlterarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPaneNovaSenhaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AlterarLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel10)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel11)))
                .addGap(47, 47, 47)
                .addComponent(btnAlterar)
                .addGap(28, 28, 28)
                .addComponent(statusAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jTabbedPane2.addTab("Alterar", Alterar);

        jLabel3.setText("Nome");

        jLabel5.setText("CPF");

        jLabel6.setText("Email");

        jLabel7.setText("Senha");

        jLabel8.setText("Confirmar Senha");

        jLabel4.setText("Usuário");

        jScrollPane3.setViewportView(TextPaneEmail);

        jScrollPane1.setViewportView(TextPaneNome);

        jScrollPane4.setViewportView(TextPaneCPF);

        jScrollPane5.setViewportView(TextPaneSenha);

        jScrollPane6.setViewportView(TextPaneCSenha);

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        jScrollPane12.setViewportView(TextPaneLoginCadastrar);

        javax.swing.GroupLayout CadastroLayout = new javax.swing.GroupLayout(Cadastro);
        Cadastro.setLayout(CadastroLayout);
        CadastroLayout.setHorizontalGroup(
            CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statusCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4))
                    .addComponent(Cadastrar))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        CadastroLayout.setVerticalGroup(
            CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroLayout.createSequentialGroup()
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CadastroLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)))
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CadastroLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel7)))
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CadastroLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Cadastrar", Cadastro);

        jLabel12.setText("Tela de Login - Sistema de Estoque");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        String username = TextPaneLoginLogar.getText();
        String password = TextAreaSenha.getText();
        boolean result = false;
        Conexao con = new Conexao();
        
        LoginDAO consulta = new LoginDAO(con);
        
        // Cria padrão para verificar dados de entrada 
        Pattern p = Pattern.compile("[^A-Za-z0-9]*"); 
        
        //Verifica se os dados são válidos -> previne SQL Injections (só aceita letras e números)
        if(!p.matcher(username).matches() && !p.matcher(password).matches()){
            result = consulta.getLogin(username, password);
            if(result){
                statusLogin.setText("Login realizado com sucesso!");
            }
            else{
                statusLogin.setText("'Usuário' ou 'Senha' Inválido(s)");
            }
        }
        else{
            statusLogin.setText("Digite apenas letras e números.");
        }
        
        con.fechaConexao();
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        String cpf = TextPaneCPF.getText();
        String username = TextPaneLoginCadastrar.getText();
        String name = TextPaneNome.getText();
        String email = TextPaneEmail.getText();
        String password = TextPaneSenha.getText();
        String password2 = TextPaneCSenha.getText();
        
        boolean result = false;
        
        Conexao con = new Conexao();
        
        CadastrarDAO consulta = new CadastrarDAO(con);
        
        Pattern p = Pattern.compile("[^A-Za-z0-9]*");
        
        if(!p.matcher(cpf).matches() && !p.matcher(username).matches() && !p.matcher(name).matches() && !p.matcher(email).matches() && !p.matcher(password).matches() && !p.matcher(password2).matches()){
            if(password.equals(password2)){ //Verifica se as Senhas informadas para cadastro são iguais
                result = consulta.getCadastro(cpf, name, email, username, password);

                if(result){
                    statusCadastro.setText("Cadastro realizado com sucesso!");
                }
                else{
                    statusCadastro.setText("Cadastro não realizado!");
                }
            }
            else{
                statusCadastro.setText("Senhas divergentes");
            }
        }
        else{
            statusCadastro.setText("Digite apenas letras e números.");
        }
        
        con.fechaConexao();
    }//GEN-LAST:event_CadastrarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        String username = jTextPaneUsuarioAlterar.getText();
        String password = jTextPaneSenhaAlterar.getText();
        String password2 = jTextPaneNovaSenhaAlterar.getText();
        boolean result = false;
        Conexao con = new Conexao();
        
        AlterarDAO consulta = new AlterarDAO(con);
        
        Pattern p = Pattern.compile("[^A-Za-z0-9]*");
        
        if(!p.matcher(username).matches() && !p.matcher(password).matches() && !p.matcher(password2).matches()){
            if (password.equals(password2)){
                result = consulta.getAltera(username, password);
                
                if(result){
                statusAlterar.setText("Alteração realizada com sucesso!");
                }
                else{
                    statusAlterar.setText("Alteração não realizada.");
                }
            }
            else{
                statusAlterar.setText("Senhas divergentes");
            }
        }
        else{
            statusAlterar.setText("Digite apenas letras e números.");
        }
        
        con.fechaConexao();
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estoque().setVisible(true);
            }
        });
        
        
        
        
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Alterar;
    private javax.swing.JButton Cadastrar;
    private javax.swing.JPanel Cadastro;
    private javax.swing.JPanel Logar;
    private javax.swing.JTextPane TextAreaSenha;
    private javax.swing.JTextPane TextPaneCPF;
    private javax.swing.JTextPane TextPaneCSenha;
    private javax.swing.JTextPane TextPaneEmail;
    private javax.swing.JTextPane TextPaneLoginCadastrar;
    private javax.swing.JTextPane TextPaneLoginLogar;
    private javax.swing.JTextPane TextPaneNome;
    private javax.swing.JTextPane TextPaneSenha;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JScrollPane jScrollPaneNovaSenhaAlterar;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextPane jTextPaneNovaSenhaAlterar;
    private javax.swing.JTextPane jTextPaneSenhaAlterar;
    private javax.swing.JTextPane jTextPaneUsuarioAlterar;
    private javax.swing.JLabel statusAlterar;
    private javax.swing.JLabel statusCadastro;
    private javax.swing.JLabel statusLogin;
    // End of variables declaration//GEN-END:variables
}
